# Generated by Django 6.0.4 on 2026-04-16 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scansession',
            name='actual_labor_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scansession',
            name='actual_parts_cost',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scansession',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
