# Generated by Django 6.0.4 on 2026-04-16 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_scansession_actual_labor_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('BASIC', 'Basique (Scans simples)'), ('PREMIUM', 'Premium (Scans + Historique)'), ('ULTIMATE', 'Ultimate (Scans + Historique + IA Predictif)')], default='BASIC', max_length=20),
        ),
    ]
