# Generated by Django 6.0.4 on 2026-04-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_vehiclemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dtcreference',
            options={'verbose_name': 'Référence DTC', 'verbose_name_plural': 'Références DTC'},
        ),
        migrations.AddField(
            model_name='dtcreference',
            name='brand',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='dtcreference',
            name='code',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='dtcreference',
            unique_together={('code', 'brand')},
        ),
    ]
