# Generated by Django 6.0.4 on 2026-04-16 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_dtcreference_options_dtcreference_brand_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('WAVE', 'Wave'), ('ORANGE', 'Orange Money'), ('MTN', 'MTN Mobile Money'), ('MOOV', 'Moov Money')], default='WAVE', max_length=20),
        ),
    ]
