# Generated by Django 6.0.4 on 2026-04-16 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtcreference',
            name='meaning',
            field=models.TextField(blank=True, null=True),
        ),
    ]
