# Generated by Django 6.0.4 on 2026-04-16 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_dtcreference_meaning'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_test_mode', models.BooleanField(default=True, verbose_name='Mode Test (Données simulées)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Globale',
                'verbose_name_plural': 'Configurations Globales',
            },
        ),
    ]
