# Generated by Django 6.0.4 on 2026-04-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtcreference',
            name='last_trained_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dtcreference',
            name='probable_causes',
            field=models.TextField(blank=True, help_text='Liste JSON des causes les plus probables', null=True),
        ),
        migrations.AddField(
            model_name='dtcreference',
            name='suggested_solutions',
            field=models.TextField(blank=True, help_text='Liste JSON des solutions les plus précises', null=True),
        ),
    ]
