# Generated by Django 6.0.4 on 2026-04-16 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_dtcreference_last_trained_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='server_ip',
            field=models.GenericIPAddressField(blank=True, help_text="L'adresse IP publique du serveur VPS pour l'accès API", null=True, verbose_name='Adresse IP du Serveur'),
        ),
    ]
