# Generated by Django 6.0.4 on 2026-04-16 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_globalsettings_server_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppNews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('content', models.TextField(verbose_name='Contenu / Description')),
                ('image_url', models.URLField(blank=True, null=True, verbose_name='URL Image (Optionnel)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
            ],
            options={
                'verbose_name': 'Nouveauté',
                'verbose_name_plural': 'Nouveautés',
                'ordering': ['-created_at'],
            },
        ),
    ]
