# Generated by Django 6.0.4 on 2026-04-16 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_appnews'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtcreference',
            name='severity',
            field=models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyen'), ('high', 'Élevé'), ('critical', 'Critique')], default='medium', max_length=10),
        ),
    ]
