# Generated by Django 6.0.4 on 2026-04-16 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_dtcreference_severity'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nom du module')),
                ('description', models.TextField(verbose_name='Description détaillée')),
                ('expected_release_date', models.DateField(verbose_name='Date de sortie prévue')),
                ('is_active', models.BooleanField(default=True, verbose_name="Afficher sur l'app")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('required_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.subscriptionplan', verbose_name='Plan requis (Optionnel)')),
            ],
            options={
                'verbose_name': 'Module à venir',
                'verbose_name_plural': 'Modules à venir',
                'ordering': ['expected_release_date'],
            },
        ),
    ]
