# Generated by Django 6.0.4 on 2026-04-16 21:32

import django_quill.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_upcomingmodule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appnews',
            name='content',
            field=django_quill.fields.QuillField(verbose_name='Contenu / Description'),
        ),
        migrations.AlterField(
            model_name='upcomingmodule',
            name='description',
            field=django_quill.fields.QuillField(verbose_name='Description détaillée'),
        ),
    ]
