# Generated by Django 6.0.4 on 2026-04-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_appnews_content_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='upcomingmodule',
            name='required_plan',
        ),
        migrations.AddField(
            model_name='appnews',
            name='eligible_plans',
            field=models.ManyToManyField(blank=True, help_text='Laissez vide pour tous les plans', to='api.subscriptionplan', verbose_name='Plans concernés'),
        ),
        migrations.AddField(
            model_name='upcomingmodule',
            name='applicable_plans',
            field=models.ManyToManyField(blank=True, to='api.subscriptionplan', verbose_name='Plans concernés'),
        ),
    ]
