# Generated by Django 6.0.4 on 2026-04-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_upcomingmodule_required_plan_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppNews',
        ),
    ]
