# Generated by Django 6.0.4 on 2026-04-16 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_delete_appnews'),
    ]

    operations = [
        migrations.CreateModel(
            name='WelcomeContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titre')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, null=True, upload_to='welcome_images/', verbose_name='Image de présentation')),
                ('video_url', models.URLField(blank=True, null=True, verbose_name='URL de la vidéo (YouTube/Vimeo/etc.)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name="Ordre d'affichage")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Contenu d'accueil",
                'verbose_name_plural': "Contenus d'accueil",
                'ordering': ['order'],
            },
        ),
    ]
