# Generated by Django 6.0.4 on 2026-04-16 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_welcomecontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='welcomecontent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='welcome/', verbose_name='Image de présentation'),
        ),
    ]
