# Generated by Django 6.0.4 on 2026-04-16 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_welcomecontent_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scansession',
            name='mileage_abs',
            field=models.PositiveIntegerField(blank=True, help_text='Kilométrage lu depuis le module ABS', null=True),
        ),
        migrations.AddField(
            model_name='scansession',
            name='mileage_dashboard',
            field=models.PositiveIntegerField(blank=True, help_text='Kilométrage affiché sur le tableau de bord', null=True),
        ),
        migrations.AddField(
            model_name='scansession',
            name='mileage_ecu',
            field=models.PositiveIntegerField(blank=True, help_text='Kilométrage lu depuis le calculateur moteur', null=True),
        ),
        migrations.CreateModel(
            name='SafetyCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_airbag_deployed', models.BooleanField(default=False)),
                ('crash_data_present', models.BooleanField(default=False)),
                ('srs_module_status', models.CharField(default='OK', max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('scan_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_check', to='api.scansession')),
            ],
            options={
                'verbose_name': 'Vérification de Sécurité',
                'verbose_name_plural': 'Vérifications de Sécurité',
            },
        ),
    ]
