# Generated by Django 6.0.4 on 2026-04-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_scansession_mileage_abs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scansession',
            name='scan_type',
            field=models.CharField(choices=[('DIAGNOSTIC', 'Diagnostic initial'), ('VERIFICATION', 'Vérification après effacement')], default='DIAGNOSTIC', max_length=20),
        ),
    ]
