# Generated by Django 6.0.4 on 2026-04-17 00:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_scansession_scan_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('MECHANIC', 'Mécanicien / Garagiste'), ('FLEET_OWNER', 'Propriétaire / Gestionnaire de Flotte')], default='MECHANIC', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='fleet_owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'FLEET_OWNER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fleet_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='IoTDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei', models.CharField(max_length=20, unique=True)),
                ('serial_number', models.CharField(max_length=50, unique=True)),
                ('installed_at', models.DateTimeField(blank=True, null=True)),
                ('last_ping', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('INACTIVE', 'Inactif'), ('STOLEN', 'Volé/Perdu')], default='INACTIVE', max_length=20)),
                ('vehicle', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='iot_device', to='api.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='PredictiveAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('BATTERY', 'Batterie Faible'), ('ENGINE', 'Anomalie Moteur'), ('MAINTENANCE', 'Entretien Conseillé'), ('THEFT', 'Suspicion de Vol/Siphonnage'), ('DRIVING', 'Conduite Dangereuse')], max_length=20)),
                ('severity', models.CharField(choices=[('INFO', 'Information'), ('WARNING', 'Avertissement'), ('CRITICAL', 'Critique')], default='INFO', max_length=10)),
                ('message', models.TextField()),
                ('probability_score', models.FloatField(default=0.0, help_text="Confiance de l'IA (0-1)")),
                ('is_resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predictive_alerts', to='api.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='TelemetryData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('voltage', models.FloatField(help_text='Tension batterie (V)')),
                ('fuel_level', models.FloatField(help_text='Niveau carburant %')),
                ('rpm', models.IntegerField(blank=True, null=True)),
                ('speed', models.IntegerField(blank=True, null=True)),
                ('engine_load', models.FloatField(blank=True, null=True)),
                ('coolant_temp', models.IntegerField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('accel_x', models.FloatField(blank=True, null=True)),
                ('accel_y', models.FloatField(blank=True, null=True)),
                ('accel_z', models.FloatField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_history', to='api.iotdevice')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_data', to='api.vehicle')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', 'timestamp'], name='api_telemet_vehicle_9ef69d_idx')],
            },
        ),
    ]
