# Generated by Django 6.0.4 on 2026-04-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_user_user_type_vehicle_fleet_owner_iotdevice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='location',
            field=models.CharField(blank=True, help_text='Localisation géographique', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shop_name',
            field=models.CharField(blank=True, help_text='Nom du garage ou de la flotte', max_length=150, null=True),
        ),
    ]
