# Generated by Django 6.0.4 on 2026-04-17 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_user_location_user_shop_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='target_user_type',
            field=models.CharField(choices=[('MECHANIC', 'Mécanicien / Garagiste'), ('FLEET_OWNER', 'Propriétaire / Gestionnaire de Flotte')], default='MECHANIC', help_text="Type d'utilisateur ciblé par ce plan", max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('BASIC', 'Basique (Scans simples)'), ('PREMIUM', 'Premium (Scans + Historique)'), ('ULTIMATE', 'Ultimate (Scans + Historique + IA Predictif)'), ('FLEET_BASIC', 'Flotte Basique'), ('FLEET_PRO', 'Flotte Pro')], default='BASIC', max_length=20),
        ),
    ]
