# Generated by Django 6.0.4 on 2026-04-17 14:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_subscriptionplan_target_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'INDIVIDUAL'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='scansession',
            name='scan_type',
            field=models.CharField(choices=[('DIAGNOSTIC', 'Diagnostic initial'), ('VERIFICATION', 'Vérification après effacement'), ('EXPERT', "Expertise d'occasion")], default='DIAGNOSTIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='target_user_type',
            field=models.CharField(choices=[('MECHANIC', 'Mécanicien / Garagiste'), ('FLEET_OWNER', 'Propriétaire / Gestionnaire de Flotte'), ('INDIVIDUAL', 'Particulier / Personnel')], default='MECHANIC', help_text="Type d'utilisateur ciblé par ce plan", max_length=20),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('BASIC', 'Basique (Scans simples)'), ('PREMIUM', 'Premium (Scans + Historique)'), ('ULTIMATE', 'Ultimate (Scans + Historique + IA Predictif)'), ('FLEET_BASIC', 'Flotte Basique'), ('FLEET_PRO', 'Flotte Pro'), ('PERSONAL_BASIC', 'Personnel Basique'), ('PERSONAL_PREMIUM', 'Personnel Premium')], default='BASIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('MECHANIC', 'Mécanicien / Garagiste'), ('FLEET_OWNER', 'Propriétaire / Gestionnaire de Flotte'), ('INDIVIDUAL', 'Particulier / Personnel')], default='MECHANIC', max_length=20),
        ),
    ]
