# Generated by Django 6.0.4 on 2026-04-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_vehicle_owner_alter_scansession_scan_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_used_trial',
            field=models.BooleanField(default=False, help_text="Indique si l'utilisateur a déjà utilisé sa période d'essai"),
        ),
        migrations.AlterField(
            model_name='subscriptionplan',
            name='tier',
            field=models.CharField(choices=[('BASIC', 'Basique (Scans simples)'), ('PREMIUM', 'Premium (Scans + Historique)'), ('ULTIMATE', 'Ultimate (Scans + Historique + IA Predictif)'), ('FLEET_BASIC', 'Flotte Basique'), ('FLEET_PRO', 'Flotte Pro'), ('PERSONAL_BASIC', 'Personnel Basique'), ('PERSONAL_PREMIUM', 'Personnel Premium'), ('TRIAL', "Période d'Essai (Gratuit)")], default='BASIC', max_length=20),
        ),
    ]
