# Generated by Django 6.0.4 on 2026-04-20 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_subscription_user_alter_subscription_mechanic'),
    ]

    operations = [
        migrations.AddField(
            model_name='dtcreference',
            name='symptoms',
            field=models.TextField(blank=True, help_text='Liste JSON des symptômes courants', null=True),
        ),
        migrations.AddField(
            model_name='dtcreference',
            name='tips',
            field=models.TextField(blank=True, help_text='Conseil pratique pour le mécanicien', null=True),
        ),
        migrations.AddField(
            model_name='dtcreference',
            name='warnings',
            field=models.TextField(blank=True, help_text='Avertissement sur les risques si non traité', null=True),
        ),
    ]
