# Generated by Django 6.0.4 on 2026-04-26 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_add_symptoms_tips_warnings_to_dtcreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='chassis_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
