# Generated by Django 6.0.4 on 2026-04-26 12:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_vehicle_chassis_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scansession',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.mechanic'),
        ),
    ]
