# Generated by Django 6.0.4 on 2026-04-26 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_scansession_mechanic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telemetrydata',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='telemetry_history', to='api.iotdevice'),
        ),
        migrations.AlterField(
            model_name='telemetrydata',
            name='fuel_level',
            field=models.FloatField(blank=True, help_text='Niveau carburant %', null=True),
        ),
        migrations.AlterField(
            model_name='telemetrydata',
            name='voltage',
            field=models.FloatField(blank=True, help_text='Tension batterie (V)', null=True),
        ),
    ]
