# Generated by Django 6.0.4 on 2026-04-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_alter_telemetrydata_device_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='telemetrydata',
            name='throttle',
            field=models.FloatField(blank=True, help_text='Position papillon %', null=True),
        ),
    ]
