# Generated by Django 6.0.4 on 2026-04-26 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_telemetrydata_throttle'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionalEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('start_month', models.PositiveSmallIntegerField(help_text='1 pour Janvier, 12 pour Décembre')),
                ('end_month', models.PositiveSmallIntegerField()),
                ('recommended_checks', models.JSONField(default=list, help_text='Liste des types de rappels conseillés')),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('OIL_CHANGE', 'Vidange Moteur'), ('AIR_FILTER', 'Filtre à Air (Saison des poussières)'), ('AC_SERVICE', 'Entretien Climatisation'), ('TYRES', 'Vérification Pneus (Saison des pluies)'), ('TECHNICAL_CONTROL', 'Contrôle Technique'), ('INSURANCE', 'Assurance'), ('OBD_CHECK', 'Scan Préventif OBD')], max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_mileage', models.PositiveIntegerField(blank=True, null=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_reminders', to='api.vehicle')),
            ],
        ),
    ]
