# Generated by Django 6.0.4 on 2026-04-26 15:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_appnotification'),
    ]

    operations = [
        migrations.AddField(
            model_name='appnotification',
            name='appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='api.appointment'),
        ),
    ]
