# Generated by Django 6.0.4 on 2026-04-27 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_chatmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scansession',
            name='found_dtcs',
        ),
        migrations.CreateModel(
            name='ScanSessionDTC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('confirmed', 'Confirmé'), ('pending', 'En attente (non confirmé)'), ('permanent', 'Permanent')], default='confirmed', max_length=20)),
                ('dtc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.dtcreference')),
                ('scan_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_dtcs', to='api.scansession')),
            ],
            options={
                'unique_together': {('scan_session', 'dtc')},
            },
        ),
    ]
