# Generated by Django 6.0.4 on 2026-04-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_remove_scansession_found_dtcs_scansessiondtc'),
    ]

    operations = [
        migrations.AddField(
            model_name='scansession',
            name='found_dtcs',
            field=models.ManyToManyField(through='api.ScanSessionDTC', to='api.dtcreference'),
        ),
    ]
