# Generated by Django 6.0.4 on 2026-04-28 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_scansession_found_dtcs'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanic',
            name='is_expert',
            field=models.BooleanField(default=False, help_text='Indique si le mécanicien est enregistré comme expert sur la carte'),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mechanic',
            name='specialties',
            field=models.TextField(blank=True, help_text='Liste des spécialités (ex: Expert Ford, Électricien)', null=True),
        ),
    ]
