# Generated by Django 6.0.4 on 2026-04-28 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_review'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('scan_session__isnull', False), ('appointment__isnull', False), _connector='OR'), name='review_must_have_intervention'),
        ),
    ]
