# Generated by Django 6.0.4 on 2026-04-28 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_review_review_must_have_intervention'),
    ]

    operations = [
        migrations.CreateModel(
            name='SparePartStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du magasin')),
                ('location_name', models.CharField(max_length=255, verbose_name='Quartier/Ville (ex: Adjamé)')),
                ('address', models.TextField(blank=True, verbose_name='Adresse complète')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Téléphone')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stores/')),
            ],
            options={
                'verbose_name': 'Magasin de pièces',
                'verbose_name_plural': 'Magasins de pièces',
            },
        ),
        migrations.AlterField(
            model_name='scansession',
            name='mechanic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='scansessions', to='api.mechanic'),
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la pièce (ex: Vanne EGR)')),
                ('brand', models.CharField(blank=True, max_length=100, verbose_name='Marque de la pièce (ex: Bosch)')),
                ('price', models.IntegerField(verbose_name='Prix (FCFA)')),
                ('stock_status', models.CharField(choices=[('IN_STOCK', 'En stock'), ('OUT_OF_STOCK', 'Rupture'), ('ON_ORDER', 'Sur commande')], default='IN_STOCK', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='parts/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compatible_dtcs', models.ManyToManyField(blank=True, related_name='recommended_parts', to='api.dtcreference')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='api.sparepartstore')),
            ],
            options={
                'verbose_name': 'Pièce détachée',
                'verbose_name_plural': 'Pièces détachées',
            },
        ),
    ]
