# Generated by Django 6.0.4 on 2026-04-28 14:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0042_sparepartstore_alter_scansession_mechanic_sparepart'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sparepart',
            options={'verbose_name': 'Pièce en stock', 'verbose_name_plural': 'Pièces en stock'},
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='compatible_dtcs',
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Nom précis (ex: Vanne EGR Toyota 2010)'),
        ),
        migrations.CreateModel(
            name='SparePartCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la catégorie (ex: Vanne EGR)')),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='part_categories/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('compatible_dtcs', models.ManyToManyField(blank=True, related_name='spare_part_categories', to='api.dtcreference')),
            ],
            options={
                'verbose_name': 'Nomenclature / Catégorie de pièce',
                'verbose_name_plural': 'Nomenclature / Catégories de pièces',
            },
        ),
        migrations.AddField(
            model_name='sparepart',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instances', to='api.sparepartcategory'),
        ),
    ]
