# Generated by Django 6.0.4 on 2026-04-28 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_alter_sparepart_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.appointment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='scan_session',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='review', to='api.scansession'),
        ),
    ]
