# Generated by Django 6.0.4 on 2026-04-28 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0044_alter_review_appointment_alter_review_scan_session'),
    ]

    operations = [
        migrations.CreateModel(
            name='TowTruck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom / Entreprise')),
                ('phone', models.CharField(max_length=20, verbose_name='Numéro de téléphone')),
                ('city', models.CharField(max_length=100, verbose_name='Ville')),
                ('district', models.CharField(blank=True, max_length=100, null=True, verbose_name='Quartier')),
                ('is_available', models.BooleanField(default=True, verbose_name='Disponible')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Remorqueur',
                'verbose_name_plural': '🚀 Remorqueurs',
                'ordering': ['city', 'district'],
            },
        ),
    ]
