# Generated by Django 6.0.4 on 2026-05-09 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0046_feature_subscriptionplan_features'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleBaseline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avg_rpm', models.FloatField(blank=True, null=True)),
                ('avg_coolant_temp', models.FloatField(blank=True, null=True)),
                ('avg_oil_temp', models.FloatField(blank=True, null=True)),
                ('avg_engine_load', models.FloatField(blank=True, null=True)),
                ('avg_voltage', models.FloatField(blank=True, null=True)),
                ('avg_fuel_trim_st', models.FloatField(blank=True, null=True)),
                ('avg_fuel_trim_lt', models.FloatField(blank=True, null=True)),
                ('avg_map_pressure', models.FloatField(blank=True, null=True)),
                ('avg_iat', models.FloatField(blank=True, null=True)),
                ('avg_throttle', models.FloatField(blank=True, null=True)),
                ('std_rpm', models.FloatField(blank=True, null=True)),
                ('std_coolant_temp', models.FloatField(blank=True, null=True)),
                ('std_engine_load', models.FloatField(blank=True, null=True)),
                ('std_voltage', models.FloatField(blank=True, null=True)),
                ('sample_count', models.IntegerField(default=0, help_text='Nombre de lectures utilisées pour calculer la baseline')),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('is_mature', models.BooleanField(default=False, help_text='True si >= 500 lectures (baseline fiable)')),
                ('vehicle', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='baseline', to='api.vehicle')),
            ],
            options={
                'verbose_name': 'Baseline véhicule',
                'verbose_name_plural': 'Baselines véhicules',
            },
        ),
        migrations.CreateModel(
            name='VehicleMLModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('VEHICLE', 'Véhicule spécifique'), ('BRAND_MODEL', 'Marque + Modèle'), ('GLOBAL', 'Modèle global')], default='GLOBAL', max_length=20)),
                ('brand', models.CharField(blank=True, help_text='Marque si scope=BRAND_MODEL', max_length=50)),
                ('model_name', models.CharField(blank=True, help_text='Modèle si scope=BRAND_MODEL', max_length=50)),
                ('model_file', models.FileField(blank=True, null=True, upload_to='ml_models/')),
                ('algorithm', models.CharField(default='RandomForest', max_length=50)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('recall', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('training_samples', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=False, help_text='Activer pour utilisation en production')),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ml_models', to='api.vehicle')),
            ],
            options={
                'verbose_name': 'Modèle ML',
                'verbose_name_plural': 'Modèles ML',
                'ordering': ['-trained_at'],
            },
        ),
        migrations.CreateModel(
            name='VehiclePIDHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('rpm', models.FloatField(blank=True, null=True)),
                ('coolant_temp', models.FloatField(blank=True, null=True)),
                ('oil_temp', models.FloatField(blank=True, null=True)),
                ('engine_load', models.FloatField(blank=True, null=True)),
                ('voltage', models.FloatField(blank=True, null=True)),
                ('speed', models.FloatField(blank=True, null=True)),
                ('throttle', models.FloatField(blank=True, null=True)),
                ('fuel_level', models.FloatField(blank=True, null=True)),
                ('fuel_trim_st', models.FloatField(blank=True, null=True)),
                ('fuel_trim_lt', models.FloatField(blank=True, null=True)),
                ('map_pressure', models.FloatField(blank=True, null=True)),
                ('iat', models.FloatField(blank=True, null=True)),
                ('o2_upstream', models.FloatField(blank=True, null=True)),
                ('o2_downstream', models.FloatField(blank=True, null=True)),
                ('maf', models.FloatField(blank=True, null=True)),
                ('has_anomaly', models.BooleanField(default=False, help_text='True si une anomalie IA a été détectée')),
                ('anomaly_severity', models.CharField(blank=True, help_text='critical/high/medium/low', max_length=20)),
                ('anomaly_codes', models.JSONField(default=list, help_text='Liste des codes DTC virtuels détectés')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pid_history', to='api.vehicle')),
            ],
            options={
                'verbose_name': 'Historique PID',
                'verbose_name_plural': 'Historiques PID',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['vehicle', 'timestamp'], name='api_vehicle_vehicle_e09737_idx'), models.Index(fields=['vehicle', 'has_anomaly'], name='api_vehicle_vehicle_7ede90_idx')],
            },
        ),
    ]
