# Generated by Django 6.0.4 on 2026-05-15 10:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_add_vehicle_baseline_pid_history_ml_model'),
    ]

    operations = [
        migrations.RunSQL(
            sql="ALTER TABLE api_upcomingmodule CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE api_upcomingmodule CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;",
            hints={'model_name': 'upcomingmodule'},
        ),
        migrations.RunSQL(
            sql="ALTER TABLE api_upcomingmodule_applicable_plans CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;",
            reverse_sql="ALTER TABLE api_upcomingmodule_applicable_plans CONVERT TO CHARACTER SET utf8 COLLATE utf8_general_ci;",
        ),
    ]
